//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appraisal_t
    {
        public System.Guid AppId { get; set; }
        public string EmpSkills { get; set; }
        public string EmpProjects { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> DoAssessment { get; set; }
        public Nullable<System.DateTime> DoAssessmentDisc { get; set; }
        public Nullable<System.DateTime> DoAssessorCompletion { get; set; }
        public Nullable<System.DateTime> DoFinalization { get; set; }
        public string SelfOverall { get; set; }
        public string AssessorOverAll { get; set; }
        public string FinalOverAll { get; set; }
        public string RecPromotion { get; set; }
        public string NotPromoting { get; set; }
        public string Understanding { get; set; }
        public string Responsibility { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string Weightage { get; set; }
        public Nullable<int> Status { get; set; }
        public string SkillRevComment { get; set; }
        public string SkillRevRating { get; set; }
        public string ProRevComment { get; set; }
        public string ProRevRating { get; set; }
        public string ProAppOtherCmnt { get; set; }
    }
}
