//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PerformanceAppEntities : DbContext
    {
        public PerformanceAppEntities()
            : base("name=PerformanceAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appraisal_t> Appraisal_t { get; set; }
        public DbSet<Employee_t> Employee_t { get; set; }
        public DbSet<EmpProject_t> EmpProject_t { get; set; }
        public DbSet<EmpSkills_t> EmpSkills_t { get; set; }
        public DbSet<Parameter_t> Parameter_t { get; set; }
        public DbSet<Projects_t> Projects_t { get; set; }
        public DbSet<Role_t> Role_t { get; set; }
        public DbSet<Skills_t> Skills_t { get; set; }
        public DbSet<Objective_t> Objective_t { get; set; }
        public DbSet<Log_t> Log_t { get; set; }
    }
}
