//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_t
    {
        public int Emp_Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Reviewer { get; set; }
        public Nullable<int> Appraiser { get; set; }
        public Nullable<System.DateTime> Dateofjoining { get; set; }
        public string Location { get; set; }
        public Nullable<int> LastAppRating { get; set; }
        public Nullable<System.Guid> DesigId { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public string Email { get; set; }
        public Nullable<int> PwdReset { get; set; }
    }
}
