//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_t
    {
        public int LogId { get; set; }
        public string Error_Message { get; set; }
        public string Page { get; set; }
        public string InnerException { get; set; }
        public string Method { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
