//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objective_t
    {
        public string Newskillacquired { get; set; }
        public Nullable<System.DateTime> LearningPurchasing { get; set; }
        public string SkillImprovisationa { get; set; }
        public string SkillImprovisationb { get; set; }
        public Nullable<System.DateTime> SkillImprovisationc { get; set; }
        public string InnovativeThoughts { get; set; }
        public Nullable<System.DateTime> Formulatingthedesignforhandling { get; set; }
        public string CertificationsToBeAchievedGeneric { get; set; }
        public Nullable<System.DateTime> OraclePreSales { get; set; }
        public string CertificationsToBeAchievedproduct { get; set; }
        public Nullable<System.DateTime> OCPINV { get; set; }
        public string CertificationsToBeAchievedManagement { get; set; }
        public string CertificationsToBeAchievedManagementa { get; set; }
        public Nullable<System.DateTime> CertificationsToBeAchievedManagementb { get; set; }
        public string KnowledgeSharingSessions { get; set; }
        public Nullable<System.DateTime> PrepartaionofIndepth { get; set; }
        public string WhitePapers { get; set; }
        public Nullable<System.DateTime> ImplementationconsiderationforINV { get; set; }
        public string SelfMotivating { get; set; }
        public Nullable<System.DateTime> TeamBuilding { get; set; }
        public string Attitude { get; set; }
        public Nullable<System.DateTime> HighlyPositive { get; set; }
        public string Commitment { get; set; }
        public Nullable<System.DateTime> CustomerDelight { get; set; }
        public string Communication { get; set; }
        public string Communicationa { get; set; }
        public Nullable<System.DateTime> Communicationb { get; set; }
        public string Provideyourinput { get; set; }
        public string Provideyourinputa { get; set; }
        public string Provideyourinputb { get; set; }
        public string Provideyourinputc { get; set; }
        public int ObjectiveID { get; set; }
        public Nullable<int> EmpId { get; set; }
    }
}
